import React from 'react';

export default () =>
    <>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida viverra volutpat. Mauris scelerisque tempor accumsan. Curabitur porta vulputate risus eget condimentum. Nunc sagittis ornare erat sed pulvinar. Cras sit amet accumsan nunc. Etiam mattis velit at arcu dapibus, a fermentum sem efficitur. Cras vitae mauris accumsan, tristique sapien eget, auctor nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed nibh nunc, sollicitudin et lacus sed, suscipit lobortis elit. Praesent ut metus et sem accumsan placerat nec in libero. Nullam aliquet sit amet risus sit amet accumsan. Praesent metus felis, sagittis et scelerisque sed, venenatis eu velit. Donec ornare ut mi et facilisis.

    Nunc aliquam justo nisl, ac semper ex sollicitudin vel. Phasellus ac maximus urna. Fusce tempus non risus et lacinia. Ut gravida augue a urna pharetra consequat eu at nibh. Etiam tempus sed est sed laoreet. Nam augue arcu, commodo sit amet scelerisque et, congue ut eros. Curabitur id lobortis justo. Vestibulum tempor sapien lobortis, finibus eros id, condimentum nibh. Nulla tincidunt iaculis libero.
    
    Proin tellus orci, feugiat sit amet semper ut, malesuada sit amet ipsum. Cras ac enim sed elit auctor malesuada. Pellentesque lobortis mattis magna id dapibus. Maecenas consectetur velit vitae arcu gravida posuere. Donec at sapien hendrerit, ultricies metus et, imperdiet justo. Sed vehicula, elit ut eleifend eleifend, augue mauris tincidunt turpis, et imperdiet enim orci id diam. Ut ut mi ut nisi sodales dignissim. Donec rhoncus commodo magna nec porta. Vivamus nec congue lorem. Sed aliquet eleifend luctus. Aliquam lacinia mollis felis at sollicitudin. Aliquam a orci imperdiet lectus viverra tempor. Vivamus elementum est mi. Sed dictum pulvinar tortor. Donec laoreet lorem nec erat bibendum imperdiet. Sed facilisis lobortis egestas.
    
    Duis lectus lorem, ornare sit amet mauris ut, venenatis interdum velit. Ut vulputate arcu sit amet ipsum rutrum, id sodales dui laoreet. Nunc feugiat facilisis massa vitae aliquet. Praesent rhoncus rutrum bibendum. Sed ornare, ipsum in fermentum porttitor, diam odio tincidunt ipsum, vel pellentesque augue diam vel velit. Aenean dolor lectus, molestie at varius ut, pharetra consequat orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc metus ante, egestas nec tristique ut, tristique vel eros.
    
    Vivamus varius sapien convallis, tristique quam et, accumsan leo. Nulla condimentum maximus odio vitae sagittis. In eu ante eu diam posuere commodo at eget nunc. Fusce et ex purus. Pellentesque et fringilla purus, vel molestie enim. Sed eget consequat tellus. Nam suscipit libero non metus fringilla, vulputate faucibus elit elementum.
    </>